# Generated by Django 4.2.2 on 2023-07-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Info',
            fields=[
                ('Client_Name', models.CharField(max_length=500)),
                ('Client_GST', models.CharField(max_length=500)),
                ('Client_Email', models.CharField(max_length=200)),
                ('Client_Password', models.CharField(max_length=500)),
                ('Client_Phone', models.IntegerField()),
                ('Client_Id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
