# Generated by Django 4.2.2 on 2023-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLogin', '0002_clientinfo_delete_client_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='Client_Phone',
            field=models.CharField(max_length=20),
        ),
    ]
