# Generated by Django 4.2.2 on 2023-07-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLogin', '0003_alter_clientinfo_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='Client_Id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
