# Generated by Django 4.2.2 on 2023-07-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLogin', '0004_remove_clientinfo_id_alter_clientinfo_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientinfo',
            old_name='Client_Id',
            new_name='id',
        ),
    ]
