# Generated by Django 4.2.2 on 2023-10-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLogin', '0005_rename_client_id_clientinfo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='Company_Address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='Company_Area',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='Company_City',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='Company_Pincode',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
