# Generated by Django 4.2.2 on 2023-10-22 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bookings', '0001_initial'),
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Billing_Lr_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Billing_Lr_Number', to='Bookings.bookings'),
        ),
    ]
