# Generated by Django 4.2.2 on 2023-10-26 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLogin', '0006_clientinfo_company_address_clientinfo_company_area_and_more'),
        ('Billing', '0003_remove_billing_client_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Payment_Client_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Billing_client_id', to='CustomerLogin.clientinfo'),
        ),
    ]
