# Generated by Django 4.2.2 on 2023-10-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0004_billing_payment_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='Payment_Client_id',
            new_name='Payment_Client',
        ),
    ]
