# Generated by Django 4.2.2 on 2024-01-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_Info',
            fields=[
                ('Driver_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Driver_Name', models.CharField(max_length=25)),
                ('Lisence_Number', models.CharField(max_length=15)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Native_State', models.CharField(max_length=10)),
                ('Native_City', models.CharField(max_length=15)),
                ('Native_Address', models.CharField(max_length=50)),
                ('Native_Pincode', models.CharField(max_length=6)),
                ('Emergency_Contact', models.CharField(max_length=10)),
                ('Blood_group', models.CharField(max_length=5)),
            ],
        ),
    ]
