# Generated by Django 4.2.2 on 2023-10-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BranchLogin', '0002_rename_branch_id_branchlogininfo_id'),
        ('CustomerLogin', '0005_rename_client_id_clientinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialManifest',
            fields=[
                ('Lr_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Order_Id', models.CharField(max_length=20)),
                ('Pickup_City', models.CharField(max_length=20)),
                ('Delivery_City', models.CharField(max_length=20)),
                ('Delivery_Type', models.CharField(max_length=10)),
                ('Consignee_Name', models.CharField(max_length=20)),
                ('Consignee_GST', models.CharField(max_length=20)),
                ('Consignee_Delivery_Address', models.CharField(max_length=100)),
                ('Consignee_Delivery_Area', models.CharField(max_length=30)),
                ('Total_Consignment_Weight', models.IntegerField(max_length=6)),
                ('Total_Article', models.IntegerField(max_length=5)),
                ('Booking_Date', models.DateField()),
                ('Booking_Time', models.TimeField()),
                ('Invoice_Number', models.CharField(max_length=250)),
                ('Ewaybill_Number', models.CharField(max_length=250)),
                ('Pickup_Status', models.CharField(max_length=15)),
                ('Client_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consginor_Id', to='CustomerLogin.clientinfo')),
                ('Delivery_Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_branch_partialManifest', to='BranchLogin.branchlogininfo')),
                ('Pickup_Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_branch_partialManifest', to='BranchLogin.branchlogininfo')),
            ],
        ),
    ]
