# Generated by Django 4.2.2 on 2023-10-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartialManifest', '0002_partialmanifest_consignee_delivery_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialmanifest',
            name='Consignee_Delivery_Contact',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
