# Generated by Django 4.2.2 on 2023-10-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartialManifest', '0003_alter_partialmanifest_consignee_delivery_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialmanifest',
            name='Consignee_Delivery_Contact',
            field=models.CharField(default='', max_length=10),
        ),
    ]
