# Generated by Django 4.2.2 on 2023-10-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartialManifest', '0004_alter_partialmanifest_consignee_delivery_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialmanifest',
            name='Pickup_Status',
            field=models.CharField(max_length=30),
        ),
    ]
