# Generated by Django 4.2.2 on 2023-10-11 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerLogin', '0005_rename_client_id_clientinfo_id'),
        ('BranchLogin', '0002_rename_branch_id_branchlogininfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindManifestBooking',
            fields=[
                ('Order_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Total_Consignment_Weight', models.IntegerField()),
                ('Total_Article', models.IntegerField()),
                ('Pickup_Truck', models.CharField(default='', max_length=15)),
                ('Pickup_Date', models.DateField()),
                ('Pickup_Time', models.TimeField()),
                ('Pickup_Status', models.CharField(max_length=15)),
                ('Client_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerLogin.clientinfo')),
                ('Delivery_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_branch_blindmanifests', to='BranchLogin.branchlogininfo')),
                ('Pickup_City', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pickup_branch_blindmanifests', to='BranchLogin.branchlogininfo')),
            ],
        ),
    ]
