# Generated by Django 4.2.2 on 2023-10-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlindManifestBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindmanifestbooking',
            name='Pickup_Status',
            field=models.CharField(max_length=50),
        ),
    ]
