# Generated by Django 4.2.2 on 2023-10-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerLogin', '0005_rename_client_id_clientinfo_id'),
        ('BlindManifestBooking', '0002_alter_blindmanifestbooking_pickup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindmanifestbooking',
            name='Client_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientinfo_clientid', to='CustomerLogin.clientinfo'),
        ),
    ]
