# Generated by Django 4.2.2 on 2023-10-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlindManifestBooking', '0004_blindmanifestbooking_delivery_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindmanifestbooking',
            name='Total_Consignment',
            field=models.IntegerField(default=0),
        ),
    ]
