# Generated by Django 4.2.2 on 2023-07-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchLoginInfo',
            fields=[
                ('Branch_Name', models.CharField(max_length=500)),
                ('Branch_Address', models.CharField(max_length=500)),
                ('Branch_City', models.CharField(max_length=500)),
                ('Branch_State', models.CharField(max_length=200)),
                ('Branch_Email', models.CharField(max_length=500)),
                ('Branch_Password', models.CharField(max_length=20)),
                ('Branch_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
