# Generated by Django 4.2.2 on 2023-07-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BranchLogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchlogininfo',
            old_name='Branch_Id',
            new_name='id',
        ),
    ]
