# Generated by Django 4.2.2 on 2023-10-23 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerLogin', '0006_clientinfo_company_address_clientinfo_company_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('City', models.CharField(max_length=20)),
                ('City_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('Route_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=20)),
                ('Destination_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_City_id', to='ClientRateTable.city')),
                ('Origin_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origin_City_id', to='ClientRateTable.city')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Charge_By', models.CharField(max_length=10)),
                ('Charge_per_unit_kg', models.IntegerField()),
                ('Hamali_Charge_Flag', models.CharField(max_length=1)),
                ('Hamali_Charge', models.IntegerField()),
                ('Door_Dly_Charge', models.IntegerField()),
                ('Pickup_Charge', models.IntegerField()),
                ('Client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Billing_Client_id', to='CustomerLogin.clientinfo')),
                ('Route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Billingconsignment_route_id', to='ClientRateTable.route')),
            ],
        ),
    ]
