# Generated by Django 4.2.2 on 2023-10-22 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BranchLogin', '0002_rename_branch_id_branchlogininfo_id'),
        ('CustomerLogin', '0006_clientinfo_company_address_clientinfo_company_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('Lr_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Order_Id', models.CharField(max_length=20)),
                ('Consignee_Name', models.CharField(max_length=20)),
                ('Consignee_GST', models.CharField(max_length=20)),
                ('Consignee_Delivery_Address', models.CharField(max_length=100)),
                ('Consignee_Area', models.CharField(max_length=15)),
                ('Consignee_City', models.CharField(max_length=15)),
                ('Consignee_Delivery_Contact', models.IntegerField()),
                ('Consignee_Delivery_Pincoe', models.IntegerField()),
                ('Invoice_Number', models.CharField(max_length=250)),
                ('Ewaybill_Number', models.CharField(max_length=250)),
                ('Delivery_Type', models.CharField(max_length=10)),
                ('Total_Consignment_Weight', models.IntegerField(max_length=6)),
                ('Total_Article', models.IntegerField(max_length=5)),
                ('Booking_Date', models.DateField()),
                ('Booking_Time', models.TimeField()),
                ('Delivery_Status', models.CharField(max_length=15)),
                ('Payment_Type', models.CharField(max_length=15)),
                ('Client_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerLogin.clientinfo')),
                ('Delivery_Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_branch_id', to='BranchLogin.branchlogininfo')),
                ('Payment_Client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_client_id', to='CustomerLogin.clientinfo')),
                ('Pickup_Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_branch_id', to='BranchLogin.branchlogininfo')),
            ],
        ),
    ]
