# Generated by Django 4.2.2 on 2023-10-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='Consignee_Delivery_Pincoe',
            new_name='Consignee_Delivery_Pincode',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Consignee_Delivery_Contact',
            field=models.CharField(max_length=10),
        ),
    ]
