# Generated by Django 4.2.2 on 2023-10-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_rename_consignee_delivery_pincoe_bookings_consignee_delivery_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Delivery_Status',
            field=models.CharField(max_length=50),
        ),
    ]
