# Generated by Django 4.2.2 on 2023-10-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_alter_bookings_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='Payment_Client_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='Payment_By',
            field=models.CharField(default='', max_length=15),
        ),
    ]
