# Generated by Django 4.2.2 on 2023-10-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_remove_bookings_payment_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Pickup_Type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
